name: Build
on: [ push ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Get Version
        run: | 
          echo "::set-output name=version::$(grep version gradle.properties | cut -d "=" -f2 | sed -e 's/^[[:space:]]*//')"
          echo "::set-output name=mcversion::$(grep mcVersion gradle.properties | cut -d "=" -f2 | sed -e 's/^[[:space:]]*//')"
        id: version
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
      - name: Release jar
        run: |
          mkdir -p target
          cp build/libs/atelier-paperclip-${{ steps.version.outputs.version }}-reobf.jar ./target/atelierclip-${{ steps.version.outputs.mcversion }}.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.mcversion }}"
          prerelease: false
          title: "Atelier ${{ steps.version.outputs.mcversion }} Release ${{ steps.date.outputs.date }}"
          files: ./target/atelier-${{ steps.version.outputs.mcversion }}.jar
