name: Build
on: [ push ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew build -x test createReobfPaperclipJar --stacktrace
      - name: Get Version
        run: echo "::set-output name=version::$(grep version gradle.properties | cut -d "=" -f2)"
        id: version
      - name: Get MC Version
        run: echo "::set-output name=mcversion::$(grep mcVersion gradle.properties | cut -d "=" -f2)"
        id: mcversion
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
      - name: Setup release jar
        run: |
          mkdir -p target
          cp build/libs/ateliersmp-paperclip-${{ steps.version.outputs.version }}-reobf.jar ./target/ateliersmp-${{ steps.mcversion.outputs.mcversion }}.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.mcversion.outputs.mcversion }}"
          prerelease: false
          title: "AtelierMC Release ${{ steps.date.outputs.date }}"
          files: ./target/ateliersmp-${{ steps.mcversion.outputs.mcversion }}.jar
